changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
        - "feat"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
        - "bugfix"
    - title: "🧰 Maintenance & Documentation"
      labels:
        - "chore"
        - "dependencies"
        - "documentation"
        - "docs"
  exclude:
    labels:
      - "ignore"
      - "skip-changelog"
